# Site settings
title: ContinualAI
description: 'A Non-profit Research Organization and Open Community on <br/><strong>Continual Learning</strong> for <strong>AI</strong>'
descriptionMeta: 'The first research organization on Continual/Lifelong Deep Learning'
url: 'http://continualai.org'
baseurl: ''
google_analytics: 'UA-65263066-3'
disqus_shortname: ''

author:
  name: 'ContinualAI'
  email: contact@continualai.org
  twitter_username: ContinualAI
  facebook_username: ContinualAI
  github_username:  ContinualAI  

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
paginate_path: /blog/page:num/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']

