# Site settings
title: Continuous AI
description: 'The first Hub and collaborative project on <br/><strong>Continuous/Lifelong Deep Learning </strong>'
url: 'http://continuosai.com'
baseurl: ''
google_analytics: ''
disqus_shortname: ''

author:
  name: 'Vincenzo Lomonaco'
  email: vincenzo.lomonaco AT unibo.it
  twitter_username: v_lomonaco
  facebook_username: lomonaco
  github_username:  Gengiolo
  linkedin_username:  vincenzo

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
paginate_path: /blog/page:num/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']

