# Site settings
title: Continual AI
description: 'An Open Community of Researchers and Enthusiasts on <br/><strong>Continual/Lifelong Learning</strong> and <strong>AI</strong>'
descriptionMeta: 'The first Hub and collaborative wiki on Continual/Lifelong Deep Learning'
url: 'http://continuosai.org'
baseurl: ''
google_analytics: ''
disqus_shortname: ''

author:
  name: 'Continual AI'
  email: contact@continualai.org
  twitter_username: ContinualAI
  facebook_username: ContinualAI
  github_username:  ContinualAI  

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
paginate_path: /blog/page:num/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']

