# Setup
title:        ContinuousAI
tagline:      The first Hub and collaborative project on Continuous Learning with Deep Nets
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       Vincenzo Lomonaco
  url:        http://vincenzolomonaco.com 

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
